table Region
	lineageTag: bca583de-764e-4d89-9f57-4f9b7afa671f

	column System
		dataType: string
		displayFolder: 1. Region Hierarchy
		lineageTag: 33bdc3d4-f515-4abe-9c2b-b07cbf859c2a
		summarizeBy: none
		sourceColumn: System

		annotation SummarizationSetBy = Automatic

	column 'Interplanetary Region'
		dataType: string
		displayFolder: 1. Region Hierarchy
		lineageTag: e5e4b390-0dcc-4018-b87c-b484a852f032
		summarizeBy: none
		sourceColumn: Interplanetary Region

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		displayFolder: 1. Region Hierarchy
		lineageTag: 85ec7ff6-21a1-4ccc-bdb0-391f173c7cbb
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column Station
		dataType: string
		displayFolder: 1. Region Hierarchy
		lineageTag: 448ce04b-4b37-4836-a906-9cbeed4310be
		summarizeBy: none
		sourceColumn: Station

		annotation SummarizationSetBy = Automatic

	column 'Station Type'
		dataType: string
		displayFolder: 2. Region Attributes
		lineageTag: 143c4d29-e3be-4b74-9cc2-f2f5b2e31c5c
		summarizeBy: none
		sourceColumn: Station Type

		annotation SummarizationSetBy = Automatic

	column 'Territory Directors'
		dataType: string
		displayFolder: 3. Managers
		lineageTag: a55a008d-d15b-4c72-ac32-796786fb4cce
		summarizeBy: none
		sourceColumn: Territory Directors

		annotation SummarizationSetBy = Automatic

	column All
		dataType: string
		displayFolder: 1. Region Hierarchy
		lineageTag: 01dabba0-927a-447c-933e-dd4282827050
		summarizeBy: none
		sourceColumn: All

		annotation SummarizationSetBy = Automatic

	column 'Station Sales Managers'
		dataType: string
		displayFolder: 3. Managers
		lineageTag: d38439ea-70ae-4a7f-82b1-6cdd6536ba53
		summarizeBy: none
		sourceColumn: Station Sales Managers

		annotation SummarizationSetBy = Automatic

	column 'System Regional Managers'
		dataType: string
		displayFolder: 3. Managers
		lineageTag: b59ca628-8da1-4052-aa67-ab015c55aaa1
		summarizeBy: none
		sourceColumn: System Regional Managers

		annotation SummarizationSetBy = Automatic

	column 'System Sales Directors'
		dataType: string
		displayFolder: 3. Managers
		lineageTag: af710796-8d11-4cc9-964f-6571ccfc7f0a
		summarizeBy: none
		sourceColumn: System Sales Directors

		annotation SummarizationSetBy = Automatic

	column 'Tax Rate'
		dataType: double
		isHidden
		formatString: #,##0.000
		displayFolder: 2. Region Attributes
		lineageTag: 39630edd-0932-46c0-9e86-5db2c308b51a
		summarizeBy: none
		sourceColumn: Tax Rate

		annotation SummarizationSetBy = Automatic

	column 'Creature Threat Level'
		dataType: string
		displayFolder: 4. Risk Profile
		lineageTag: d1a70001-0001-0001-0001-000000000001
		summarizeBy: none
		sourceColumn: Creature Threat Level

		annotation SummarizationSetBy = Automatic

	column 'Piracy Risk'
		dataType: string
		displayFolder: 4. Risk Profile
		lineageTag: d1a70001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: Piracy Risk

		annotation SummarizationSetBy = Automatic

	column 'Convoy Requirement'
		dataType: string
		displayFolder: 4. Risk Profile
		lineageTag: d1a70001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Convoy Requirement

		annotation SummarizationSetBy = Automatic

	hierarchy 'Regional Hierarchy'
		displayFolder: 1. Region Hierarchy
		lineageTag: 8ce16331-fb01-4dfb-bd38-da99652a4893

		level All
			lineageTag: d0892c44-a314-4400-a33c-1c9e05de3679
			column: All

		level System
			lineageTag: eb24e180-a00e-4f4f-9b9f-03f0c2c33521
			column: System

		level 'Interplanetary Region'
			lineageTag: df0d47d9-4330-4447-8fc4-7a3dead1f50d
			column: 'Interplanetary Region'

		level Territory
			lineageTag: 006fd1c2-f102-4ed6-b80b-677e2e392747
			column: Territory

		level Station
			lineageTag: d6c1f01c-580a-45be-ba9f-a0ce66a12255
			column: Station

	partition Region = m
		mode: import
		queryGroup: Tables
		source =
				let
				    Source = Csv.Document(File.Contents(#"DataFolder" & "\Region.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"System", type text}, {"Interplanetary Region", type text}, {"Territory", type text},
				        {"Station", type text}, {"Station Type", type text}, {"Territory Directors", type text},
				        {"All", type text}, {"Station Sales Managers", type text}, {"System Regional Managers", type text},
				        {"System Sales Directors", type text}, {"Tax Rate", type number},
				        {"Creature Threat Level", type text}, {"Piracy Risk", type text}, {"Convoy Requirement", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

