table Shipments
	lineageTag: e864ea7c-38b6-44bc-92b6-e167034b7f19

	/// Count of invoice line items.
	measure '# Invoice Lines' = COUNTROWS ( Shipments )
		formatString: #,##0
		displayFolder: Measures
		lineageTag: 0fab4eac-d56c-45a6-a5c8-8c3ceb38ba83

	/// Gross Profit in EUR (Revenue minus COGS), converted via Budget Rate.
	measure 'Gross Profit' =
			SUMX (
			    Shipments,
			    ( Shipments[Net Invoice Value] - Shipments[Net Invoice COGS] )
			        / RELATED ( 'Budget Rate'[Rate] )
			)
		displayFolder: Measures
		lineageTag: f1000001-0001-0001-0001-000000000001

		formatStringDefinition =
				VAR _Value = SELECTEDMEASURE()
				VAR _FormatString =
				    DaxLib.FormatString.DynamicUnits (
				        _Value,
				        "",
				        "",
				        "€",
				        ""
				    )
				RETURN _FormatString

	/// Gross Margin as a percentage of Revenue.
	measure 'Gross Margin %' = DIVIDE ( [Gross Profit], [Revenue] )
		formatString: #,##0.0%;-#,##0.0%;#,##0.0%
		displayFolder: Measures
		lineageTag: f1000001-0001-0001-0001-000000000002

	/// Total Revenue in EUR (Net Invoice Value converted via Budget Rate).
	measure Revenue =
			SUMX (
			    Shipments,
			    Shipments[Net Invoice Value]
			        / RELATED ( 'Budget Rate'[Rate] )
			)
		displayFolder: Measures
		lineageTag: f1000001-0001-0001-0001-000000000003

		formatStringDefinition =
				VAR _Value = SELECTEDMEASURE()
				VAR _FormatString =
				    DaxLib.FormatString.DynamicUnits (
				        _Value,
				        "",
				        "",
				        "€",
				        ""
				    )
				RETURN _FormatString

	/// Total Cost of Goods Sold in EUR.
	measure COGS =
			SUMX (
			    Shipments,
			    Shipments[Net Invoice COGS]
			        / RELATED ( 'Budget Rate'[Rate] )
			)
		displayFolder: Measures
		lineageTag: f1000001-0001-0001-0001-000000000004

		formatStringDefinition =
				VAR _Value = SELECTEDMEASURE()
				VAR _FormatString =
				    DaxLib.FormatString.DynamicUnits (
				        _Value,
				        "",
				        "",
				        "€",
				        ""
				    )
				RETURN _FormatString

	/// Gross Profit from the same period one year prior, used for year-over-year comparisons.
	measure 'Gross Profit (PY)' =
			CALCULATE (
			    [Gross Profit],
			    DATEADD ( 'Date'[Date], -1, YEAR ),
			    REMOVEFILTERS ( 'Date'[IsThisYear], 'Date'[IsDateInScope] )
			)
		displayFolder: Measures
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80299

		formatStringDefinition =
				VAR _Value = SELECTEDMEASURE()
				VAR _FormatString =
				    DaxLib.FormatString.DynamicUnits (
				        _Value,
				        "",
				        "",
				        "€",
				        ""
				    )
				RETURN _FormatString

	/// Year-over-year change in Gross Profit expressed as a percentage.
	measure 'Gross Profit vs PY %' = DIVIDE ( [Gross Profit] - [Gross Profit (PY)], [Gross Profit (PY)] )
		formatString: ↑#,##0.0%;↓#,##0.0%;#,##0.0%
		displayFolder: Measures
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80301

	/// Gross Margin % from the same period one year prior, used for year-over-year comparisons.
	measure 'Gross Margin % (PY)' =
			CALCULATE (
			    [Gross Margin %],
			    DATEADD ( 'Date'[Date], -1, YEAR ),
			    REMOVEFILTERS ( 'Date'[IsThisYear], 'Date'[IsDateInScope] )
			)
		formatString: #,##0.0%;-#,##0.0%;#,##0.0%
		displayFolder: Measures
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80302

	/// Year-over-year change in Gross Margin % expressed in percentage points. Excludes incomplete current month.
	measure 'Gross Margin % vs PY pp' =
			VAR _RefIsEndOfMonth = [RefDate] = EOMONTH ( [RefDate], 0 )
			VAR _LastCompleteMonthEnd =
			    IF ( _RefIsEndOfMonth, EOMONTH ( [RefDate], 0 ), EOMONTH ( [RefDate], -1 ) )
			VAR _GM =
			    CALCULATE ( [Gross Margin %], 'Date'[Date] <= _LastCompleteMonthEnd )
			VAR _GMPY =
			    CALCULATE ( [Gross Margin % (PY)], 'Date'[Date] <= _LastCompleteMonthEnd )
			RETURN
			    100 * ( _GM - _GMPY )
		formatString: ↑0.#\p\p;↓0.#\p\p
		displayFolder: Measures
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80303

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'CF - KPI Title Gross Margin %' =
			VAR _Value = [Gross Margin %]
			VAR _MonthLabel =
			    IF (
			        HASONEVALUE ( 'Date'[Calendar Month Year (ie Jan 21)] ),
			        " in " & VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] ),
			        ""
			    )
			RETURN
			    FORMAT ( _Value, "#,##0.0%" ) & " Gross Margin" & _MonthLabel
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80304

	measure 'CF - Last Complete Month and PY Month Gross Margin %' =
			VAR _RefIsEndOfMonth =
			    [RefDate] = EOMONTH( [RefDate], 0 )
			VAR _LastCompleteMonthEnd =
			    IF(
			        _RefIsEndOfMonth,
			        EOMONTH( [RefDate], 0 ),
			        EOMONTH( [RefDate], -1 )
			    )
			VAR _PYMonthEnd =
			    EOMONTH( _LastCompleteMonthEnd, -12 )
			VAR _CurrentMonthEnd =
			    EOMONTH( MAX( 'Date'[Date] ), 0 )
			RETURN
			    IF(
			        _CurrentMonthEnd = _LastCompleteMonthEnd
			            || _CurrentMonthEnd = _PYMonthEnd,
			        [Gross Margin %]
			    )
		formatString: #,##0.0%;-#,##0.0%;#,##0.0%
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: a11f3ebe-1528-4ad9-8c83-03085b8c68e8

	measure 'CF - Current Incomplete and Last Complete Month Gross Margin %' =
			VAR _RefIsEndOfMonth = [RefDate] = EOMONTH ( [RefDate], 0 )
			  VAR _LastCompleteMonthEnd =
			      IF ( _RefIsEndOfMonth, EOMONTH ( [RefDate], 0 ), EOMONTH ( [RefDate],
			  -1 ) )
			  VAR _RefMonthEnd = EOMONTH ( [RefDate], 0 )
			  VAR _EndOfMonth = EOMONTH ( MAX ( 'Date'[Date] ), 0 )
			  RETURN
			      IF (
			          NOT _RefIsEndOfMonth
			              && ( _EndOfMonth = _RefMonthEnd || _EndOfMonth =
			  _LastCompleteMonthEnd ),
			          [Gross Margin %]
			      )
		formatString: #,##0.0%;-#,##0.0%;#,##0.0%
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: 3a969d6e-3913-46a8-b72e-021d7b44b056

	measure 'CF - Last Complete Month and 12 Preceding Months Gross Margin %' =
			VAR _RefIsEndOfMonth = [RefDate] = EOMONTH ( [RefDate], 0 )
			  VAR _LastCompleteMonthEnd =
			      IF ( _RefIsEndOfMonth, EOMONTH ( [RefDate], 0 ), EOMONTH ( [RefDate],
			  -1 ) )
			  VAR _WindowStart = EOMONTH ( [RefDate], -14 )
			  VAR _EndOfMonth = EOMONTH ( MAX ( 'Date'[Date] ), 0 )
			  RETURN
			      IF (
			          _EndOfMonth <= _LastCompleteMonthEnd && _EndOfMonth >
			  _WindowStart,
			          [Gross Margin %]
			      )
		formatString: #,##0.0%;-#,##0.0%;#,##0.0%
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: 8f6ed42f-8b8a-492d-bb63-1b1bd654a2c3

	/// Total shipped units (Net Invoice Quantity).
	measure '# Units Sold' = SUM ( Shipments[Net Invoice Quantity] )
		displayFolder: Measures
		lineageTag: f1000001-0001-0001-0001-000000000010

		formatStringDefinition =
				VAR _Value = SELECTEDMEASURE()
				VAR _FormatString =
				    DaxLib.FormatString.DynamicUnits (
				        _Value,
				        "",
				        "",
				        "",
				        ""
				    )
				RETURN _FormatString

	measure 'CF - KPI Title Gross Profit' =
			VAR _Value = [Gross Profit]
			VAR _FormatString =
			    DaxLib.FormatString.DynamicUnits (
			        _Value,
			        "",
			        "",
			        "€",
			        ""
			    )
			RETURN
			    FORMAT ( _Value, _FormatString ) & " Gross Profit"
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80320

	measure 'CF - KPI Subtitle Gross Profit vs PY' =
			VAR _RefIsEndOfMonth = [RefDate] = EOMONTH ( [RefDate], 0 )
			VAR _LastCompleteMonthEnd =
			    IF ( _RefIsEndOfMonth, EOMONTH ( [RefDate], 0 ), EOMONTH ( [RefDate], -1 ) )
			VAR _Change =
			    CALCULATE ( [Gross Profit vs PY %], 'Date'[Date] <= _LastCompleteMonthEnd )
			VAR _MinDate = MIN ( Shipments[Billing Date] )
			VAR _MaxDate = _LastCompleteMonthEnd
			VAR _PYMin = EDATE ( _MinDate, -12 )
			VAR _PYMax = EDATE ( _MaxDate, -12 )
			VAR _PYMinMonth = FORMAT ( _PYMin, "MMM" )
			VAR _PYMaxMonth = FORMAT ( _PYMax, "MMM" )
			VAR _PYMinYear = FORMAT ( _PYMin, "'YY" )
			VAR _PYMaxYear = FORMAT ( _PYMax, "'YY" )
			VAR _PYMinLabel = _PYMinMonth & " " & _PYMinYear
			VAR _PYMaxLabel = _PYMaxMonth & " " & _PYMaxYear
			VAR _Suffix =
			    IF (
			        _PYMinLabel = _PYMaxLabel,
			        " vs " & _PYMinLabel,
			        IF (
			            _PYMinYear = _PYMaxYear,
			            " vs PY (" & _PYMinMonth & " – " & _PYMaxLabel & ")",
			            " vs PY (" & _PYMinLabel & " – " & _PYMaxLabel & ")"
			        )
			    )
			VAR _FormatString =
			    DaxLib.FormatString.RelativeToTarget.Percents (
			        "PREFIX",
			        1,
			        "ARROWS",
			        "",
			        _Suffix
			    )
			RETURN
			    FORMAT ( _Change, _FormatString )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80321

	measure 'CF - Time Range Label' =
			VAR _MinDate = MIN ( 'Date'[Date] )
			VAR _MaxDate = MIN ( MAX ( 'Date'[Date] ), [RefDate] )
			VAR _SameMonth =
			    YEAR ( _MinDate ) = YEAR ( _MaxDate )
			        && MONTH ( _MinDate ) = MONTH ( _MaxDate )
			VAR _MinLabel = FORMAT ( _MinDate, "MMM D, 'YY" )
			VAR _MaxLabel = FORMAT ( _MaxDate, "MMM D, 'YY" )
			RETURN
			    IF (
			        ISBLANK ( _MinDate ),
			        "",
			        IF (
			            _SameMonth,
			            FORMAT ( _MinDate, "MMM 'YY" ),
			            _MinLabel & " – " & _MaxLabel
			        )
			    )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80323

	measure 'CF - Last Complete Month Gross Margin % vs PY pp' =
			VAR _RefIsEndOfMonth =
			    [RefDate] = EOMONTH ( [RefDate], 0 )
			VAR _LastCompleteMonthEnd =
			    IF (
			        _RefIsEndOfMonth,
			        EOMONTH ( [RefDate], 0 ),
			        EOMONTH ( [RefDate], -1 )
			    )
			VAR _CurrentMonthEnd =
			    EOMONTH ( MAX ( 'Date'[Date] ), 0 )
			VAR _Change = [Gross Margin % vs PY pp]
			VAR _FormatString =
			    DaxLib.FormatString.RelativeToTarget.Numeric (
			        "PREFIX",
			        1,
			        "TRIANGLES",
			        "",
			        "pp"
			    )
			RETURN
			    IF (
			        _CurrentMonthEnd = _LastCompleteMonthEnd,
			        FORMAT ( _Change, _FormatString )
			    )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: fc9b595f-fea8-423f-afff-abece8b80322

	measure 'CF - Scatter Chart X Min' =
			VAR _Order = SELECTEDVALUE ( 'ScatterChartXMetricSelector'[ScatterChartXAxis Order] )
			VAR _Table =
			    ADDCOLUMNS (
			        VALUES ( Customer[Customer Sold-To Name] ),
			        "@v",
			            SWITCH (
			                _Order,
			                0, CALCULATE ( [COGS] ),
			                1, CALCULATE ( [Gross Margin %] ),
			                2, CALCULATE ( [Gross Profit] ),
			                3, CALCULATE ( [# Invoice Lines] ),
			                4, CALCULATE ( [Revenue] ),
			                5, CALCULATE ( [# Units Sold] )
			            )
			    )
			VAR _Min = MINX ( _Table, [@v] )
			VAR _Max = MAXX ( _Table, [@v] )
			VAR _Range = _Max - _Min
			RETURN
			    _Min - _Range * 0.1
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: f1000001-0001-0001-0001-000000000018

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF - Scatter Chart X Max' =
			VAR _Order = SELECTEDVALUE ( 'ScatterChartXMetricSelector'[ScatterChartXAxis Order] )
			VAR _Table =
			    ADDCOLUMNS (
			        VALUES ( Customer[Customer Sold-To Name] ),
			        "@v",
			            SWITCH (
			                _Order,
			                0, CALCULATE ( [COGS] ),
			                1, CALCULATE ( [Gross Margin %] ),
			                2, CALCULATE ( [Gross Profit] ),
			                3, CALCULATE ( [# Invoice Lines] ),
			                4, CALCULATE ( [Revenue] ),
			                5, CALCULATE ( [# Units Sold] )
			            )
			    )
			VAR _Min = MINX ( _Table, [@v] )
			VAR _Max = MAXX ( _Table, [@v] )
			VAR _Range = _Max - _Min
			RETURN
			    _Max + _Range * 0.1
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: f1000001-0001-0001-0001-000000000019

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF - Scatter Chart Y Min' =
			VAR _Order = SELECTEDVALUE ( 'ScatterChartYMetricSelector'[ScatterChartYAxis Order] )
			VAR _Table =
			    ADDCOLUMNS (
			        VALUES ( Customer[Customer Sold-To Name] ),
			        "@v",
			            SWITCH (
			                _Order,
			                0, CALCULATE ( [COGS] ),
			                1, CALCULATE ( [Gross Margin %] ),
			                2, CALCULATE ( [Gross Profit] ),
			                3, CALCULATE ( [# Invoice Lines] ),
			                4, CALCULATE ( [Revenue] ),
			                5, CALCULATE ( [# Units Sold] )
			            )
			    )
			VAR _Min = MINX ( _Table, [@v] )
			VAR _Max = MAXX ( _Table, [@v] )
			VAR _Range = _Max - _Min
			RETURN
			    _Min - _Range * 0.1
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: f1000001-0001-0001-0001-000000000020

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF - Scatter Chart Y Max' =
			VAR _Order = SELECTEDVALUE ( 'ScatterChartYMetricSelector'[ScatterChartYAxis Order] )
			VAR _Table =
			    ADDCOLUMNS (
			        VALUES ( Customer[Customer Sold-To Name] ),
			        "@v",
			            SWITCH (
			                _Order,
			                0, CALCULATE ( [COGS] ),
			                1, CALCULATE ( [Gross Margin %] ),
			                2, CALCULATE ( [Gross Profit] ),
			                3, CALCULATE ( [# Invoice Lines] ),
			                4, CALCULATE ( [Revenue] ),
			                5, CALCULATE ( [# Units Sold] )
			            )
			    )
			VAR _Min = MINX ( _Table, [@v] )
			VAR _Max = MAXX ( _Table, [@v] )
			VAR _Range = _Max - _Min
			RETURN
			    _Max + _Range * 0.1
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: f1000001-0001-0001-0001-000000000021

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF - Tooltip Gross Margin %' =
			VAR _RefIsEndOfMonth = [RefDate] = EOMONTH ( [RefDate], 0 )
			VAR _LastCompleteMonthEnd =
			    IF ( _RefIsEndOfMonth, EOMONTH ( [RefDate], 0 ), EOMONTH ( [RefDate], -1 ) )
			VAR _Value =
			    CALCULATE ( [Gross Margin %], 'Date'[Date] <= _LastCompleteMonthEnd )
			VAR _MinDate = MIN ( Shipments[Billing Date] )
			VAR _MaxDate = _LastCompleteMonthEnd
			VAR _SameMonth =
			    YEAR ( _MinDate ) = YEAR ( _MaxDate )
			        && MONTH ( _MinDate ) = MONTH ( _MaxDate )
			VAR _MinLabel = FORMAT ( _MinDate, "MMM 'YY" )
			VAR _MaxLabel = FORMAT ( _MaxDate, "MMM 'YY" )
			VAR _DateRange =
			    IF (
			        _SameMonth,
			        _MinLabel,
			        _MinLabel & " – " & _MaxLabel
			    )
			RETURN
			    IF (
			        NOT ISBLANK ( _Value ),
			        FORMAT ( _Value, "#,##0.0%" ) & " (" & _DateRange & ")"
			    )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: cf5a0001-0001-0001-0001-000000000001

	measure 'CF - Tooltip Gross Margin % (PY)' =
			VAR _RefIsEndOfMonth = [RefDate] = EOMONTH ( [RefDate], 0 )
			VAR _LastCompleteMonthEnd =
			    IF ( _RefIsEndOfMonth, EOMONTH ( [RefDate], 0 ), EOMONTH ( [RefDate], -1 ) )
			VAR _Value =
			    CALCULATE ( [Gross Margin % (PY)], 'Date'[Date] <= _LastCompleteMonthEnd )
			VAR _MinDate = MIN ( Shipments[Billing Date] )
			VAR _MaxDate = _LastCompleteMonthEnd
			VAR _PYMin = EDATE ( _MinDate, -12 )
			VAR _PYMax = EDATE ( _MaxDate, -12 )
			VAR _SameMonth =
			    YEAR ( _PYMin ) = YEAR ( _PYMax )
			        && MONTH ( _PYMin ) = MONTH ( _PYMax )
			VAR _MinLabel = FORMAT ( _PYMin, "MMM 'YY" )
			VAR _MaxLabel = FORMAT ( _PYMax, "MMM 'YY" )
			VAR _DateRange =
			    IF (
			        _SameMonth,
			        _MinLabel,
			        _MinLabel & " – " & _MaxLabel
			    )
			RETURN
			    IF (
			        NOT ISBLANK ( _Value ),
			        FORMAT ( _Value, "#,##0.0%" ) & " (" & _DateRange & ")"
			    )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: cf5a0001-0001-0001-0001-000000000002

	measure 'CF - Page Title Exploration' =
			VAR _Station = IF ( ISFILTERED ( Region[Station] ), SELECTEDVALUE ( Region[Station] ) )
			VAR _Brand = IF ( ISFILTERED ( Brand[Brand] ), SELECTEDVALUE ( Brand[Brand] ) )
			VAR _Customer = IF ( ISFILTERED ( Customer[Customer Sold-To Name] ), SELECTEDVALUE ( Customer[Customer Sold-To Name] ) )
			VAR _Month =
			    IF (
			        ISFILTERED ( 'Date'[Date] ) || ISFILTERED ( 'Date'[Calendar Month Year (ie Jan 21)] ),
			        SELECTEDVALUE ( 'Date'[Calendar Month Year (ie Jan 21)] )
			    )
			VAR _Subtype = IF ( ISFILTERED ( Product[Subtype] ), SELECTEDVALUE ( Product[Subtype] ) )
			VAR _Product = IF ( ISFILTERED ( Product[Product Name] ), SELECTEDVALUE ( Product[Product Name] ) )
			VAR _Material = IF ( ISFILTERED ( Product[Material] ), SELECTEDVALUE ( Product[Material] ) )
			VAR _Context =
			    COALESCE ( _Customer, _Station, _Brand, _Product, _Subtype, _Material, _Month )
			RETURN
			    IF ( ISBLANK ( _Context ), "Exploration", "Exploring: " & _Context )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: cf5a0001-0001-0001-0001-000000000003

	measure 'CF - Selected Customer Sold-To Name' = SELECTEDVALUE( Customer[Customer Sold-To Name] )
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: ff429321-92bc-40bd-b986-697515653d88

	measure 'CF - Bar Chart X Min' =
			VAR _Nudge = 0.5
			VAR _Min =
			    MINX (
			        ALLSELECTED ( 'Region'[Station] ),
			        [Gross Margin % vs PY pp]
			    )
			RETURN
			    _Min * ( 1 + _Nudge )
		formatString: 0.0
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: a14a0001-0001-0001-0001-000000000101

	measure 'CF - Bar Chart X Max' =
			VAR _Nudge = 0.4
			VAR _Max =
			    MAXX (
			        ALLSELECTED ( 'Region'[Station] ),
			        [Gross Margin % vs PY pp]
			    )
			RETURN
			    _Max * ( 1 + _Nudge )
		formatString: 0.0
		isHidden
		displayFolder: Measures\Report Objects
		lineageTag: a14a0001-0001-0001-0001-000000000102

	column 'Billing Document Number'
		dataType: string
		isHidden
		displayFolder: Columns\1. Degenerate Dimensions\Document #s
		lineageTag: 80891c7d-b84a-4f81-b676-701a8560036e
		summarizeBy: none
		sourceColumn: Billing Document Number

		annotation SummarizationSetBy = Automatic

	column 'Billing Date'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		sourceProviderType: date
		displayFolder: Columns\2. Keys\Dates
		lineageTag: 3ecdddab-f189-4960-9608-28147ac9655e
		summarizeBy: none
		sourceColumn: Billing Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Customer Key'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Columns\2. Keys
		lineageTag: 00383e87-df2b-496c-8fa2-6c332eaa6e07
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

	column 'Billing Document Line Item Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Columns\1. Degenerate Dimensions\Document #s
		lineageTag: 2d7bb6a5-1f60-464f-8c26-275762c63277
		summarizeBy: none
		sourceColumn: Billing Document Line Item Number

		annotation SummarizationSetBy = Automatic

	column 'Product Key'
		dataType: int64
		isHidden
		displayFolder: Columns\2. Keys
		lineageTag: 2206902c-3b4b-4b19-bc0f-a4d1b133f937
		summarizeBy: none
		sourceColumn: Product Key

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		displayFolder: Columns\2. Keys\Dates
		lineageTag: 26b8ed72-1ee8-4732-b37e-89fbcded5bc1
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'OTD Indicator'
		dataType: string
		isHidden
		displayFolder: Columns\2. Keys
		lineageTag: 61c6d81f-1fb6-420d-a6bf-aaaff17aedcb
		summarizeBy: none
		sourceColumn: OTD Indicator

		annotation SummarizationSetBy = Automatic

	column 'Billing Document Type Code'
		dataType: string
		isHidden
		displayFolder: Columns\2. Keys
		lineageTag: f08cfa92-9f3b-4abe-8925-00d00d77d15a
		summarizeBy: none
		sourceColumn: Billing Document Type Code

		annotation SummarizationSetBy = Automatic

	column 'Local Currency'
		dataType: string
		isHidden
		displayFolder: Columns\2. Keys
		lineageTag: b00f4fb9-8ed5-4972-b62a-352eac69d319
		summarizeBy: none
		sourceColumn: Local Currency

		annotation SummarizationSetBy = Automatic

	column 'Delivery Cost'
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: 2cab7bca-6b96-40ec-8270-84d9dd874335
		summarizeBy: sum
		sourceColumn: Delivery Cost

		annotation SummarizationSetBy = Automatic

	column 'Net Invoice COGS'
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: 8ac8f0a8-e780-4d46-aaba-a4b806711a51
		summarizeBy: sum
		sourceColumn: Net Invoice COGS

		annotation SummarizationSetBy = Automatic

	column 'Late Delivery Penalties'
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: 63f35167-689e-4bfd-a6d4-d3e6c7b7d6ab
		summarizeBy: sum
		sourceColumn: Late Delivery Penalties

		annotation SummarizationSetBy = Automatic

	column 'Overdue Payment Penalties'
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: d220b6b9-526e-48f9-bb37-ad55b4911012
		summarizeBy: sum
		sourceColumn: Overdue Payment Penalties

		annotation SummarizationSetBy = Automatic

	column 'Taxes & Commercial Fees'
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: 87bf78e5-838d-4135-8088-d1ab84900b17
		summarizeBy: sum
		sourceColumn: Taxes & Commercial Fees

		annotation SummarizationSetBy = Automatic

	column Freight
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: 86a9f2ce-a05f-4470-9c36-a55196785919
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

	column 'Net Invoice Value'
		dataType: double
		isHidden
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: 86af53e2-7af5-497b-b995-9d43aebbc686
		summarizeBy: sum
		sourceColumn: Net Invoice Value

		annotation SummarizationSetBy = Automatic

	column 'Net Invoice Quantity'
		dataType: int64
		isHidden
		displayFolder: Columns\0. Facts
		lineageTag: 5b447336-164e-415f-9d13-759cfa0aa0b5
		summarizeBy: sum
		sourceColumn: Net Invoice Quantity

		annotation SummarizationSetBy = Automatic

	column 'Billing to Ship Days' = DATEDIFF ( Shipments[Billing Date], Shipments[Ship Date], DAY )
		dataType: int64
		formatString: #,##0
		displayFolder: Columns\0. Facts
		lineageTag: f1000001-0001-0001-0001-000000000030
		summarizeBy: none

	partition Shipments = m
		mode: import
		queryGroup: Tables
		source =
				let
				    Source = Csv.Document(File.Contents(#"DataFolder" & "\Shipments.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Billing Document Number", type text}, {"Billing Document Line Item Number", Int64.Type},
				        {"Billing Date", type date}, {"Customer Key", Int64.Type}, {"Product Key", Int64.Type},
				        {"Ship Date", type date}, {"OTD Indicator", type text}, {"Billing Document Type Code", type text},
				        {"Local Currency", type text}, {"Delivery Cost", type number}, {"Net Invoice COGS", type number},
				        {"Late Delivery Penalties", type number}, {"Overdue Payment Penalties", type number},
				        {"Taxes & Commercial Fees", type number}, {"Freight", type number},
				        {"Net Invoice Value", type number}, {"Net Invoice Quantity", Int64.Type}
				    }),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Billing Date] >= Date.From(#"RangeStart") and [Billing Date] < Date.From(#"RangeEnd")),
				    #"Excluded Svalbard" = Table.SelectRows(#"Filtered Rows", each [Customer Key] <> 48)
				in
				    #"Excluded Svalbard"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

