table 'Exchange Rate'
	lineageTag: 01ee8527-a2dc-471d-9a3d-9ccfe51284ef

	/// The type of exchange rate (e.g. spot, average).
	column 'Rate Type'
		dataType: string
		isHidden
		displayFolder: 2. Other Currency Fields
		lineageTag: 452c5cfd-c704-4b98-be56-71082368b44b
		summarizeBy: none
		sourceColumn: Rate Type

		annotation SummarizationSetBy = Automatic

	column 'From Currency'
		dataType: string
		displayFolder: 1. Select a Currency
		lineageTag: ee8bbaa9-0b3e-42bf-9d01-d907458159bc
		summarizeBy: none
		sourceColumn: From Currency

		annotation SummarizationSetBy = Automatic

	column 'To Currency'
		dataType: string
		isHidden
		displayFolder: 2. Other Currency Fields
		lineageTag: 7640e9c9-9b46-48e7-bdaa-c96bb487b625
		summarizeBy: none
		sourceColumn: To Currency

		annotation SummarizationSetBy = Automatic

	/// The currency system classification.
	column 'Currency System'
		dataType: string
		isHidden
		displayFolder: 2. Other Currency Fields
		lineageTag: ee01193c-1f42-4aec-a1fc-45db6cabfb80
		summarizeBy: none
		sourceColumn: Currency System

		annotation SummarizationSetBy = Automatic

	/// The currency exchange rate value.
	column Rate
		dataType: double
		isHidden
		formatString: #,##0.0000
		displayFolder: 2. Other Currency Fields
		lineageTag: c7c98d7b-101b-4fb0-b4b6-a1990adb1ecb
		summarizeBy: none
		sourceColumn: Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		displayFolder: 2. Other Currency Fields
		lineageTag: 024862a6-5e54-4cc6-a1d7-2b7b1f393ad6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		isHidden
		displayFolder: 2. Other Currency Fields
		lineageTag: fe0e261d-d4be-49a5-b2d0-a644f272b0eb
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Exchange Rate Composite Key'
		dataType: string
		isHidden
		displayFolder: 2. Other Currency Fields
		lineageTag: 5b3738b3-2625-4510-909a-71dd86316090
		summarizeBy: none
		sourceColumn: Exchange Rate Composite Key

		annotation SummarizationSetBy = Automatic

	partition 'Exchange Rate' = m
		mode: import
		queryGroup: Tables
		source =
				let
				    Source = Csv.Document(File.Contents(#"DataFolder" & "\Exchange Rate.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Rate Type", type text}, {"From Currency", type text}, {"To Currency", type text},
				        {"Currency System", type text}, {"Rate", type number}, {"Date", type date},
				        {"Month", type text}, {"Exchange Rate Composite Key", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

